// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/usersdata.proto

package usersdatapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsersDataSynchronization_GetComparable_FullMethodName = "/usersdata.UsersDataSynchronization/GetComparable"
	UsersDataSynchronization_GetAll_FullMethodName        = "/usersdata.UsersDataSynchronization/GetAll"
	UsersDataSynchronization_GetSlice_FullMethodName      = "/usersdata.UsersDataSynchronization/GetSlice"
	UsersDataSynchronization_UpdateSlice_FullMethodName   = "/usersdata.UsersDataSynchronization/UpdateSlice"
	UsersDataSynchronization_InsertSlice_FullMethodName   = "/usersdata.UsersDataSynchronization/InsertSlice"
)

// UsersDataSynchronizationClient is the client API for UsersDataSynchronization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersDataSynchronizationClient interface {
	GetComparable(ctx context.Context, in *GetComparableRequest, opts ...grpc.CallOption) (*GetComparableResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	GetSlice(ctx context.Context, in *GetSliceRequest, opts ...grpc.CallOption) (*GetSliceResponse, error)
	UpdateSlice(ctx context.Context, in *UpdateSliceRequest, opts ...grpc.CallOption) (*UpdateSliceResponse, error)
	InsertSlice(ctx context.Context, in *InsertSliceRequest, opts ...grpc.CallOption) (*InsertSliceResponse, error)
}

type usersDataSynchronizationClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersDataSynchronizationClient(cc grpc.ClientConnInterface) UsersDataSynchronizationClient {
	return &usersDataSynchronizationClient{cc}
}

func (c *usersDataSynchronizationClient) GetComparable(ctx context.Context, in *GetComparableRequest, opts ...grpc.CallOption) (*GetComparableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComparableResponse)
	err := c.cc.Invoke(ctx, UsersDataSynchronization_GetComparable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersDataSynchronizationClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, UsersDataSynchronization_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersDataSynchronizationClient) GetSlice(ctx context.Context, in *GetSliceRequest, opts ...grpc.CallOption) (*GetSliceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSliceResponse)
	err := c.cc.Invoke(ctx, UsersDataSynchronization_GetSlice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersDataSynchronizationClient) UpdateSlice(ctx context.Context, in *UpdateSliceRequest, opts ...grpc.CallOption) (*UpdateSliceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSliceResponse)
	err := c.cc.Invoke(ctx, UsersDataSynchronization_UpdateSlice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersDataSynchronizationClient) InsertSlice(ctx context.Context, in *InsertSliceRequest, opts ...grpc.CallOption) (*InsertSliceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertSliceResponse)
	err := c.cc.Invoke(ctx, UsersDataSynchronization_InsertSlice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersDataSynchronizationServer is the server API for UsersDataSynchronization service.
// All implementations must embed UnimplementedUsersDataSynchronizationServer
// for forward compatibility.
type UsersDataSynchronizationServer interface {
	GetComparable(context.Context, *GetComparableRequest) (*GetComparableResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	GetSlice(context.Context, *GetSliceRequest) (*GetSliceResponse, error)
	UpdateSlice(context.Context, *UpdateSliceRequest) (*UpdateSliceResponse, error)
	InsertSlice(context.Context, *InsertSliceRequest) (*InsertSliceResponse, error)
	mustEmbedUnimplementedUsersDataSynchronizationServer()
}

// UnimplementedUsersDataSynchronizationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersDataSynchronizationServer struct{}

func (UnimplementedUsersDataSynchronizationServer) GetComparable(context.Context, *GetComparableRequest) (*GetComparableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComparable not implemented")
}
func (UnimplementedUsersDataSynchronizationServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUsersDataSynchronizationServer) GetSlice(context.Context, *GetSliceRequest) (*GetSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlice not implemented")
}
func (UnimplementedUsersDataSynchronizationServer) UpdateSlice(context.Context, *UpdateSliceRequest) (*UpdateSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlice not implemented")
}
func (UnimplementedUsersDataSynchronizationServer) InsertSlice(context.Context, *InsertSliceRequest) (*InsertSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertSlice not implemented")
}
func (UnimplementedUsersDataSynchronizationServer) mustEmbedUnimplementedUsersDataSynchronizationServer() {
}
func (UnimplementedUsersDataSynchronizationServer) testEmbeddedByValue() {}

// UnsafeUsersDataSynchronizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersDataSynchronizationServer will
// result in compilation errors.
type UnsafeUsersDataSynchronizationServer interface {
	mustEmbedUnimplementedUsersDataSynchronizationServer()
}

func RegisterUsersDataSynchronizationServer(s grpc.ServiceRegistrar, srv UsersDataSynchronizationServer) {
	// If the following call pancis, it indicates UnimplementedUsersDataSynchronizationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsersDataSynchronization_ServiceDesc, srv)
}

func _UsersDataSynchronization_GetComparable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComparableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersDataSynchronizationServer).GetComparable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersDataSynchronization_GetComparable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersDataSynchronizationServer).GetComparable(ctx, req.(*GetComparableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersDataSynchronization_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersDataSynchronizationServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersDataSynchronization_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersDataSynchronizationServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersDataSynchronization_GetSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersDataSynchronizationServer).GetSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersDataSynchronization_GetSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersDataSynchronizationServer).GetSlice(ctx, req.(*GetSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersDataSynchronization_UpdateSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersDataSynchronizationServer).UpdateSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersDataSynchronization_UpdateSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersDataSynchronizationServer).UpdateSlice(ctx, req.(*UpdateSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersDataSynchronization_InsertSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersDataSynchronizationServer).InsertSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersDataSynchronization_InsertSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersDataSynchronizationServer).InsertSlice(ctx, req.(*InsertSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersDataSynchronization_ServiceDesc is the grpc.ServiceDesc for UsersDataSynchronization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersDataSynchronization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usersdata.UsersDataSynchronization",
	HandlerType: (*UsersDataSynchronizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComparable",
			Handler:    _UsersDataSynchronization_GetComparable_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _UsersDataSynchronization_GetAll_Handler,
		},
		{
			MethodName: "GetSlice",
			Handler:    _UsersDataSynchronization_GetSlice_Handler,
		},
		{
			MethodName: "UpdateSlice",
			Handler:    _UsersDataSynchronization_UpdateSlice_Handler,
		},
		{
			MethodName: "InsertSlice",
			Handler:    _UsersDataSynchronization_InsertSlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/usersdata.proto",
}
