// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/usersdata.proto

package usersdatapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comparable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comparable) Reset() {
	*x = Comparable{}
	mi := &file_proto_usersdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparable) ProtoMessage() {}

func (x *Comparable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparable.ProtoReflect.Descriptor instead.
func (*Comparable) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{0}
}

func (x *Comparable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comparable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Comparable) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Deleted       bool                   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_usersdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Payload) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Payload) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Payload) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetComparableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComparableRequest) Reset() {
	*x = GetComparableRequest{}
	mi := &file_proto_usersdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComparableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComparableRequest) ProtoMessage() {}

func (x *GetComparableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComparableRequest.ProtoReflect.Descriptor instead.
func (*GetComparableRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{2}
}

func (x *GetComparableRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetComparableRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

type GetComparableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Comparable          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComparableResponse) Reset() {
	*x = GetComparableResponse{}
	mi := &file_proto_usersdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComparableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComparableResponse) ProtoMessage() {}

func (x *GetComparableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComparableResponse.ProtoReflect.Descriptor instead.
func (*GetComparableResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{3}
}

func (x *GetComparableResponse) GetData() []*Comparable {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_usersdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetAllRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Payload             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_proto_usersdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllResponse) GetData() []*Payload {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Ids           []int64                `protobuf:"varint,3,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSliceRequest) Reset() {
	*x = GetSliceRequest{}
	mi := &file_proto_usersdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSliceRequest) ProtoMessage() {}

func (x *GetSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSliceRequest.ProtoReflect.Descriptor instead.
func (*GetSliceRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{6}
}

func (x *GetSliceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSliceRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *GetSliceRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Payload             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSliceResponse) Reset() {
	*x = GetSliceResponse{}
	mi := &file_proto_usersdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSliceResponse) ProtoMessage() {}

func (x *GetSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSliceResponse.ProtoReflect.Descriptor instead.
func (*GetSliceResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{7}
}

func (x *GetSliceResponse) GetData() []*Payload {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Data          []*Payload             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSliceRequest) Reset() {
	*x = UpdateSliceRequest{}
	mi := &file_proto_usersdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSliceRequest) ProtoMessage() {}

func (x *UpdateSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSliceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSliceRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSliceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateSliceRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *UpdateSliceRequest) GetData() []*Payload {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSliceResponse) Reset() {
	*x = UpdateSliceResponse{}
	mi := &file_proto_usersdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSliceResponse) ProtoMessage() {}

func (x *UpdateSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSliceResponse.ProtoReflect.Descriptor instead.
func (*UpdateSliceResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSliceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type InsertSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Data          []*Payload             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertSliceRequest) Reset() {
	*x = InsertSliceRequest{}
	mi := &file_proto_usersdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSliceRequest) ProtoMessage() {}

func (x *InsertSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSliceRequest.ProtoReflect.Descriptor instead.
func (*InsertSliceRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{10}
}

func (x *InsertSliceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InsertSliceRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *InsertSliceRequest) GetData() []*Payload {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertSliceResponse) Reset() {
	*x = InsertSliceResponse{}
	mi := &file_proto_usersdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSliceResponse) ProtoMessage() {}

func (x *InsertSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSliceResponse.ProtoReflect.Descriptor instead.
func (*InsertSliceResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersdata_proto_rawDescGZIP(), []int{11}
}

func (x *InsertSliceResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_usersdata_proto protoreflect.FileDescriptor

const file_proto_usersdata_proto_rawDesc = "" +
	"\n" +
	"\x15proto/usersdata.proto\x12\tusersdata\"N\n" +
	"\n" +
	"Comparable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\"\x97\x01\n" +
	"\aPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\"D\n" +
	"\x14GetComparableRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\"B\n" +
	"\x15GetComparableResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.usersdata.ComparableR\x04data\"=\n" +
	"\rGetAllRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\"8\n" +
	"\x0eGetAllResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.usersdata.PayloadR\x04data\"Q\n" +
	"\x0fGetSliceRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\x03R\x03ids\":\n" +
	"\x10GetSliceResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.usersdata.PayloadR\x04data\"j\n" +
	"\x12UpdateSliceRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.usersdata.PayloadR\x04data\"%\n" +
	"\x13UpdateSliceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"j\n" +
	"\x12InsertSliceRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.usersdata.PayloadR\x04data\"'\n" +
	"\x13InsertSliceResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids2\x98\x03\n" +
	"\x18UsersDataSynchronization\x12T\n" +
	"\rGetComparable\x12\x1f.usersdata.GetComparableRequest\x1a .usersdata.GetComparableResponse\"\x00\x12?\n" +
	"\x06GetAll\x12\x18.usersdata.GetAllRequest\x1a\x19.usersdata.GetAllResponse\"\x00\x12E\n" +
	"\bGetSlice\x12\x1a.usersdata.GetSliceRequest\x1a\x1b.usersdata.GetSliceResponse\"\x00\x12N\n" +
	"\vUpdateSlice\x12\x1d.usersdata.UpdateSliceRequest\x1a\x1e.usersdata.UpdateSliceResponse\"\x00\x12N\n" +
	"\vInsertSlice\x12\x1d.usersdata.InsertSliceRequest\x1a\x1e.usersdata.InsertSliceResponse\"\x00B:Z8github.com/niksmo/gophkeeper/proto/usersdata;usersdatapbb\x06proto3"

var (
	file_proto_usersdata_proto_rawDescOnce sync.Once
	file_proto_usersdata_proto_rawDescData []byte
)

func file_proto_usersdata_proto_rawDescGZIP() []byte {
	file_proto_usersdata_proto_rawDescOnce.Do(func() {
		file_proto_usersdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_usersdata_proto_rawDesc), len(file_proto_usersdata_proto_rawDesc)))
	})
	return file_proto_usersdata_proto_rawDescData
}

var file_proto_usersdata_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_usersdata_proto_goTypes = []any{
	(*Comparable)(nil),            // 0: usersdata.Comparable
	(*Payload)(nil),               // 1: usersdata.Payload
	(*GetComparableRequest)(nil),  // 2: usersdata.GetComparableRequest
	(*GetComparableResponse)(nil), // 3: usersdata.GetComparableResponse
	(*GetAllRequest)(nil),         // 4: usersdata.GetAllRequest
	(*GetAllResponse)(nil),        // 5: usersdata.GetAllResponse
	(*GetSliceRequest)(nil),       // 6: usersdata.GetSliceRequest
	(*GetSliceResponse)(nil),      // 7: usersdata.GetSliceResponse
	(*UpdateSliceRequest)(nil),    // 8: usersdata.UpdateSliceRequest
	(*UpdateSliceResponse)(nil),   // 9: usersdata.UpdateSliceResponse
	(*InsertSliceRequest)(nil),    // 10: usersdata.InsertSliceRequest
	(*InsertSliceResponse)(nil),   // 11: usersdata.InsertSliceResponse
}
var file_proto_usersdata_proto_depIdxs = []int32{
	0,  // 0: usersdata.GetComparableResponse.data:type_name -> usersdata.Comparable
	1,  // 1: usersdata.GetAllResponse.data:type_name -> usersdata.Payload
	1,  // 2: usersdata.GetSliceResponse.data:type_name -> usersdata.Payload
	1,  // 3: usersdata.UpdateSliceRequest.data:type_name -> usersdata.Payload
	1,  // 4: usersdata.InsertSliceRequest.data:type_name -> usersdata.Payload
	2,  // 5: usersdata.UsersDataSynchronization.GetComparable:input_type -> usersdata.GetComparableRequest
	4,  // 6: usersdata.UsersDataSynchronization.GetAll:input_type -> usersdata.GetAllRequest
	6,  // 7: usersdata.UsersDataSynchronization.GetSlice:input_type -> usersdata.GetSliceRequest
	8,  // 8: usersdata.UsersDataSynchronization.UpdateSlice:input_type -> usersdata.UpdateSliceRequest
	10, // 9: usersdata.UsersDataSynchronization.InsertSlice:input_type -> usersdata.InsertSliceRequest
	3,  // 10: usersdata.UsersDataSynchronization.GetComparable:output_type -> usersdata.GetComparableResponse
	5,  // 11: usersdata.UsersDataSynchronization.GetAll:output_type -> usersdata.GetAllResponse
	7,  // 12: usersdata.UsersDataSynchronization.GetSlice:output_type -> usersdata.GetSliceResponse
	9,  // 13: usersdata.UsersDataSynchronization.UpdateSlice:output_type -> usersdata.UpdateSliceResponse
	11, // 14: usersdata.UsersDataSynchronization.InsertSlice:output_type -> usersdata.InsertSliceResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_usersdata_proto_init() }
func file_proto_usersdata_proto_init() {
	if File_proto_usersdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_usersdata_proto_rawDesc), len(file_proto_usersdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_usersdata_proto_goTypes,
		DependencyIndexes: file_proto_usersdata_proto_depIdxs,
		MessageInfos:      file_proto_usersdata_proto_msgTypes,
	}.Build()
	File_proto_usersdata_proto = out.File
	file_proto_usersdata_proto_goTypes = nil
	file_proto_usersdata_proto_depIdxs = nil
}
